server:
  http_listen_port: 3200
  grpc_listen_port: 4317

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
        grpc:
          endpoint: 0.0.0.0:14250

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    compaction_window: 1h
    max_compaction_objects: 6
    block_retention: 1h
    compacted_block_retention: 10m

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    block:
      version: vParquet
  admin_client:
    backend: local
    local:
      path: /var/tempo/wal

querier:
  max_concurrent_queries: 100

metrics_generator:
  registry:
    enabled: true
  storage:
    path: /var/tempo/wal
  processors:
    - batch
    - attributes
    - span_metrics
    - service_graphs
  overrides:
    defaults:
      metrics_generator_processors:
        - batch
        - attributes
        - span_metrics
        - service_graphs

usage_report:
  enabled: false
