apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: x0tta6bl4-production

resources:
  # cert-manager resources
  - cert-manager/cluster-issuer.yaml
  - cert-manager/workload-certificates.yaml
  # SPIRE resources
  - spire/workload-registration.yaml
  # Istio mTLS policies
  - istio/mtls-policies.yaml

commonLabels:
  app.kubernetes.io/part-of: x0tta6bl4
  security.x0tta6bl4.io/mtls: enabled

commonAnnotations:
  description: "mTLS configuration for x0tta6bl4"
