apiVersion: v1
kind: Service
metadata:
  name: x0tta6bl4-service
  labels:
    app: x0tta6bl4
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: api
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: metrics
  - port: 4001
    targetPort: 4001
    protocol: TCP
    name: mesh
  selector:
    app: x0tta6bl4

