apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: x0tta6bl4-production

resources:
  - proxy-api-rollout.yaml
  - analysis-templates.yaml
  - istio-config.yaml

commonLabels:
  app.kubernetes.io/part-of: x0tta6bl4
  deployment-strategy: canary
