apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: x0tta6bl4-base
  namespace: x0tta6bl4

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: x0tta6bl4
  app.kubernetes.io/part-of: x0tta6bl4-mesh
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  description: "Zero-trust mesh network platform"
